Added Zachary's Quantitative Analysis portion and Aanchal's Efficient Frontier portion.
mmarovich/portfolio-analyzer pull request #9
Opened 2022-09-21 23:14 UTC by aakhanna-1909

Added Zachary's Quantitative Analysis portion and Aanchal's Efficient Frontier portion.

2022-09-21 23:15 UTC, BubbaHexinator approved these changes

2022-09-22 01:12 UTC, mmarovich requested changes

2022-09-22 01:12 UTC, mmarovich commented on modules/sharpe_ratio.py
> +  sharpe_ratio_df = pd.DataFrame([ticker_list, sharpe_ratio_list]).T
```suggestion
  # Needed to call .T method to transpose data properly
  sharpe_ratio_df = pd.DataFrame([ticker_list, sharpe_ratio_list]).T
```

2022-09-22 01:12 UTC, mmarovich commented on modules/volatility_analysis.py
> +  for ticker in tickers:
```suggestion
  each_ticker = []
  
  for ticker in tickers:
```

2022-09-22 01:12 UTC, mmarovich commented on modules/volatility_analysis.py
> +  return(volatility_df)
```suggestion
  display(volatility_df)
```

2022-09-22 01:12 UTC, mmarovich commented on modules/sp500.py
> +    return sp500_df
I think we can use code that has already been written for the "SPY" ticker.  Let's use alpaca call function to get the dataframe, and we can use the calculate returns function to get the returns, and we can retrieve this information at the start of our app, to have it ready when we need it.

2022-09-22 01:12 UTC, mmarovich commented on modules/beta.py
> +    for ticker in tickers:
```suggestion
    ticker_list = []
    
    for ticker in tickers:
```

2022-09-22 01:12 UTC, mmarovich commented on modules/mean_variance_frontier.py
> +      standard_deviation = (portfolio.loc[:, (random_ticker, "daily_returns")].std()) * np.sqrt(number_trading_days)
```suggestion
      annualized_standard_deviation = (portfolio.loc[:, (random_ticker, "daily_returns")].std()) * np.sqrt(number_trading_days)
```

2022-09-22 01:12 UTC, mmarovich commented on modules/mean_variance_frontier.py
> +      standard_deviation_returns_list.append(standard_deviation)
```suggestion
      standard_deviation_returns_list.append(annualized_standard_deviation)
```

2022-09-22 01:12 UTC, mmarovich commented on modules/mean_variance_frontier.py
> +import seaborn as sns
Delete seaborn, as it is not used.  And also, add:

`from matplotlib.axes._axes import _log as matplotlib_axes_logger
matplotlib_axes_logger.setLevel('ERROR')`

which will get rid of error in app

2022-09-22 02:21 UTC, mmarovich approved these changes

2022-09-22 02:39 UTC, closed without merging